#!/usr/bin/env bash
# Install your load balancer
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get install software-properties-common
sudo apt-get -y install haproxy

sudo echo "frontend load_balancer
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 1658-web-01 35.237.150.157:80
    server 1658-web-02 35.196.147.211:80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
