#!/usr/bin/env bash
# Nginx likes port 80, configuration of a server,
# Nginx must be running and listening on port 80 of all active IPv4 of the server
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
pkill nginx
service nginx start
