#!/usr/bin/env bash
# This bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
new_file=/var/run/holbertonscript.pid
echo $$ > "$new_file"
trap 'echo Y U no love me?!' SIGINT
trap 'echo I hate the kill command; rm $new_file; exit' SIGTERM
trap 'rm $new_file; exit' SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
