#!/usr/bin/env bash
# This bash script that displays numbers from 1 to 20, bad luck from China(4th), bad luck from Japan(9th), bad luck from Italy(17th)
str1="bad luck from China"
str2="bad luck from Japon"
str3="bad luck from Italia"
i=1
while [ "$i" -le 20 ]
	do
		case "$i" in

			4)
				echo "$i"
				echo "$str1"
				;;

			9)
				echo "$i"
				echo "$str2"
				;;

			17)
				echo "$i"
				echo "$str3"
				;;

			*)
				echo "$i"
				;;
		esac
		let "i += 1"
	done
