#!/usr/bin/env bash
# This bash script that displays the time for 12 hours and 59 minutes
i=0
while [ "$i" -le 12 ]
	do
		echo "Hour: $i"
		let "i += 1"
			j=1
			while [ "$j" -le 59 ]
				do
					echo "$j"
					let "j += 1"
				done
	done
